ISO2dict = {'AFG':'AF',
'ALB':'AL',
'DZA':'DZ',
'ASM':'AS',
'AND':'AD',
'AGO':'AO',
'AIA':'AI',
'ATA':'AQ',
'ATG':'AG',
'ARG':'AR',
'ARM':'AM',
'ABW':'AW',
'AUS':'AU',
'AUT':'AT',
'AZE':'AZ',
'BHS':'BS',
'BHR':'BH',
'BGD':'BD',
'BRB':'BB',
'BLR':'BY',
'BEL':'BE',
'BLZ':'BZ',
'BEN':'BJ',
'BMU':'BM',
'BTN':'BT',
'BOL':'BO',
'BES':'BQ',
'BIH':'BA',
'BWA':'BW',
'BVT':'BV',
'BRA':'BR',
'IOT':'IO',
'BRN':'BN',
'BGR':'BG',
'BFA':'BF',
'BDI':'BI',
'CPV':'CV',
'KHM':'KH',
'CMR':'CM',
'CAN':'CA',
'CYM':'KY',
'CAF':'CF',
'TCD':'TD',
'CHL':'CL',
'CHN':'CN',
'CXR':'CX',
'CCK':'CC',
'COL':'CO',
'COM':'KM',
'COD':'CD',
'COG':'CG',
'COK':'CK',
'CRI':'CR',
'HRV':'HR',
'CUB':'CU',
'CUW':'CW',
'CYP':'CY',
'CZE':'CZ',
'CIV':'CI',
'DNK':'DK',
'DJI':'DJ',
'DMA':'DM',
'DOM':'DO',
'ECU':'EC',
'EGY':'EG',
'SLV':'SV',
'GNQ':'GQ',
'ERI':'ER',
'EST':'EE',
'SWZ':'SZ',
'ETH':'ET',
'FLK':'FK',
'FRO':'FO',
'FJI':'FJ',
'FIN':'FI',
'FRA':'FR',
'GUF':'GF',
'PYF':'PF',
'ATF':'TF',
'GAB':'GA',
'GMB':'GM',
'GEO':'GE',
'DEU':'DE',
'GHA':'GH',
'GIB':'GI',
'GRC':'GR',
'GRL':'GL',
'GRD':'GD',
'GLP':'GP',
'GUM':'GU',
'GTM':'GT',
'GGY':'GG',
'GIN':'GN',
'GNB':'GW',
'GUY':'GY',
'HTI':'HT',
'HMD':'HM',
'VAT':'VA',
'HND':'HN',
'HKG':'HK',
'HUN':'HU',
'ISL':'IS',
'IND':'IN',
'IDN':'ID',
'IRN':'IR',
'IRQ':'IQ',
'IRL':'IE',
'IMN':'IM',
'ISR':'IL',
'ITA':'IT',
'JAM':'JM',
'JPN':'JP',
'JEY':'JE',
'JOR':'JO',
'KAZ':'KZ',
'KEN':'KE',
'KIR':'KI',
'PRK':'KP',
'KOR':'KR',
'KWT':'KW',
'KGZ':'KG',
'LAO':'LA',
'LVA':'LV',
'LBN':'LB',
'LSO':'LS',
'LBR':'LR',
'LBY':'LY',
'LIE':'LI',
'LTU':'LT',
'LUX':'LU',
'MAC':'MO',
'MDG':'MG',
'MWI':'MW',
'MYS':'MY',
'MDV':'MV',
'MLI':'ML',
'MLT':'MT',
'MHL':'MH',
'MTQ':'MQ',
'MRT':'MR',
'MUS':'MU',
'MYT':'YT',
'MEX':'MX',
'FSM':'FM',
'MDA':'MD',
'MCO':'MC',
'MNG':'MN',
'MNE':'ME',
'MSR':'MS',
'MAR':'MA',
'MOZ':'MZ',
'MMR':'MM',
'NAM':'NA',
'NRU':'NR',
'NPL':'NP',
'NLD':'NL',
'NCL':'NC',
'NZL':'NZ',
'NIC':'NI',
'NER':'NE',
'NGA':'NG',
'NIU':'NU',
'NFK':'NF',
'MNP':'MP',
'NOR':'NO',
'OMN':'OM',
'PAK':'PK',
'PLW':'PW',
'PSE':'PS',
'PAN':'PA',
'PNG':'PG',
'PRY':'PY',
'PER':'PE',
'PHL':'PH',
'PCN':'PN',
'POL':'PL',
'PRT':'PT',
'PRI':'PR',
'QAT':'QA',
'MKD':'MK',
'ROU':'RO',
'RUS':'RU',
'RWA':'RW',
'REU':'RE',
'BLM':'BL',
'SHN':'SH',
'KNA':'KN',
'LCA':'LC',
'MAF':'MF',
'SPM':'PM',
'VCT':'VC',
'WSM':'WS',
'SMR':'SM',
'STP':'ST',
'SAU':'SA',
'SEN':'SN',
'SRB':'RS',
'SYC':'SC',
'SLE':'SL',
'SGP':'SG',
'SXM':'SX',
'SVK':'SK',
'SVN':'SI',
'SLB':'SB',
'SOM':'SO',
'ZAF':'ZA',
'SGS':'GS',
'SSD':'SS',
'ESP':'ES',
'LKA':'LK',
'SDN':'SD',
'SUR':'SR',
'SJM':'SJ',
'SWE':'SE',
'CHE':'CH',
'SYR':'SY',
'TWN':'TW',
'TJK':'TJ',
'TZA':'TZ',
'THA':'TH',
'TLS':'TL',
'TGO':'TG',
'TKL':'TK',
'TON':'TO',
'TTO':'TT',
'TUN':'TN',
'TUR':'TR',
'TKM':'TM',
'TCA':'TC',
'TUV':'TV',
'UGA':'UG',
'UKR':'UA',
'ARE':'AE',
'GBR':'GB',
'UMI':'UM',
'USA':'US',
'URY':'UY',
'UZB':'UZ',
'VUT':'VU',
'VEN':'VE',
'VNM':'VN',
'VGB':'VG',
'VIR':'VI',
'WLF':'WF',
'ESH':'EH',
'YEM':'YE',
'ZMB':'ZM',
'ZWE':'ZW',
'ALA':'AX',}

ISOcountryname = {'AFG':'Afghanistan',
'ALB':'Albania',
'DZA':'Algeria',
'ASM':'American Samoa',
'AND':'Andorra',
'AGO':'Angola',
'AIA':'Anguilla',
'ATA':'Antarctica',
'ATG':'Antigua and Barbuda',
'ARG':'Argentina',
'ARM':'Armenia',
'ABW':'Aruba',
'AUS':'Australia',
'AUT':'Austria',
'AZE':'Azerbaijan',
'BHS':'Bahamas (the)',
'BHR':'Bahrain',
'BGD':'Bangladesh',
'BRB':'Barbados',
'BLR':'Belarus',
'BEL':'Belgium',
'BLZ':'Belize',
'BEN':'Benin',
'BMU':'Bermuda',
'BTN':'Bhutan',
'BOL':'Bolivia (Plurinational State of)',
'BES':'Bonaire, Sint Eustatius and Saba',
'BIH':'Bosnia and Herzegovina',
'BWA':'Botswana',
'BVT':'Bouvet Island',
'BRA':'Brazil',
'IOT':'British Indian Ocean Territory',
'BRN':'Brunei Darussalam',
'BGR':'Bulgaria',
'BFA':'Burkina Faso',
'BDI':'Burundi',
'CPV':'Cabo Verde',
'KHM':'Cambodia',
'CMR':'Cameroon',
'CAN':'Canada',
'CYM':'Cayman Islands (the)',
'CAF':'Central African Republic',
'TCD':'Chad',
'CHL':'Chile',
'CHN':'China',
'CXR':'Christmas Island',
'CCK':'Cocos (Keeling) Islands',
'COL':'Colombia',
'COM':'Comoros (the)',
'COD':'The Democratic Republic of the Congo',
'COG':'Congo',
'COK':'Cook Islands',
'CRI':'Costa Rica',
'HRV':'Croatia',
'CUB':'Cuba',
'CUW':'Curaçao',
'CYP':'Cyprus',
'CZE':'Czechia',
'CIV':'Côte d\'Ivoire',
'DNK':'Denmark',
'DJI':'Djibouti',
'DMA':'Dominica',
'DOM':'Dominican Republic',
'ECU':'Ecuador',
'EGY':'Egypt',
'SLV':'El Salvador',
'GNQ':'Equatorial Guinea',
'ERI':'Eritrea',
'EST':'Estonia',
'SWZ':'Eswatini',
'ETH':'Ethiopia',
'FLK':'Falkland Islands',
'FRO':'Faroe Islands',
'FJI':'Fiji',
'FIN':'Finland',
'FRA':'France',
'GUF':'French Guiana',
'PYF':'French Polynesia',
'ATF':'French Southern Territories',
'GAB':'Gabon',
'GMB':'Gambia (the)',
'GEO':'Georgia',
'DEU':'Germany',
'GHA':'Ghana',
'GIB':'Gibraltar',
'GRC':'Greece',
'GRL':'Greenland',
'GRD':'Grenada',
'GLP':'Guadeloupe',
'GUM':'Guam',
'GTM':'Guatemala',
'GGY':'Guernsey',
'GIN':'Guinea',
'GNB':'Guinea-Bissau',
'GUY':'Guyana',
'HTI':'Haiti',
'HMD':'Heard Island and McDonald Islands',
'VAT':'Holy See (the)',
'HND':'Honduras',
'HKG':'Hong Kong',
'HUN':'Hungary',
'ISL':'Iceland',
'IND':'India',
'IDN':'Indonesia',
'IRN':'Iran (Islamic Republic of)',
'IRQ':'Iraq',
'IRL':'Ireland',
'IMN':'Isle of Man',
'ISR':'Israel',
'ITA':'Italy',
'JAM':'Jamaica',
'JPN':'Japan',
'JEY':'Jersey',
'JOR':'Jordan',
'KAZ':'Kazakhstan',
'KEN':'Kenya',
'KIR':'Kiribati',
'PRK':'The Democratic People\'s Republic of Korea',
'KOR':'The Republic of Korea',
'KWT':'Kuwait',
'KGZ':'Kyrgyzstan',
'LAO':'The Lao People\'s Democratic Republic',
'LVA':'Latvia',
'LBN':'Lebanon',
'LSO':'Lesotho',
'LBR':'Liberia',
'LBY':'Libya',
'LIE':'Liechtenstein',
'LTU':'Lithuania',
'LUX':'Luxembourg',
'MAC':'Macao',
'MDG':'Madagascar',
'MWI':'Malawi',
'MYS':'Malaysia',
'MDV':'Maldives',
'MLI':'Mali',
'MLT':'Malta',
'MHL':'Marshall Islands (the)',
'MTQ':'Martinique',
'MRT':'Mauritania',
'MUS':'Mauritius',
'MYT':'Mayotte',
'MEX':'Mexico',
'FSM':'Federated States of Micronesia',
'MDA':'The Republic of Moldova',
'MCO':'Monaco',
'MNG':'Mongolia',
'MNE':'Montenegro',
'MSR':'Montserrat',
'MAR':'Morocco',
'MOZ':'Mozambique',
'MMR':'Myanmar',
'NAM':'Namibia',
'NRU':'Nauru',
'NPL':'Nepal',
'NLD':'Netherlands (the)',
'NCL':'New Caledonia',
'NZL':'New Zealand',
'NIC':'Nicaragua',
'NER':'Niger (the)',
'NGA':'Nigeria',
'NIU':'Niue',
'NFK':'Norfolk Island',
'MNP':'Northern Mariana Islands (the)',
'NOR':'Norway',
'OMN':'Oman',
'PAK':'Pakistan',
'PLW':'Palau',
'PSE':'Palestine, State of',
'PAN':'Panama',
'PNG':'Papua New Guinea',
'PRY':'Paraguay',
'PER':'Peru',
'PHL':'Philippines (the)',
'PCN':'Pitcairn',
'POL':'Poland',
'PRT':'Portugal',
'PRI':'Puerto Rico',
'QAT':'Qatar',
'MKD':'Republic of North Macedonia',
'ROU':'Romania',
'RUS':'Russian Federation (the)',
'RWA':'Rwanda',
'REU':'Réunion',
'BLM':'Saint Barthélemy',
'SHN':'Saint Helena, Ascension and Tristan da Cunha',
'KNA':'Saint Kitts and Nevis',
'LCA':'Saint Lucia',
'MAF':'Saint Martin (French part)',
'SPM':'Saint Pierre and Miquelon',
'VCT':'Saint Vincent and the Grenadines',
'WSM':'Samoa',
'SMR':'San Marino',
'STP':'Sao Tome and Principe',
'SAU':'Saudi Arabia',
'SEN':'Senegal',
'SRB':'Serbia',
'SYC':'Seychelles',
'SLE':'Sierra Leone',
'SGP':'Singapore',
'SXM':'Sint Maarten (Dutch part)',
'SVK':'Slovakia',
'SVN':'Slovenia',
'SLB':'Solomon Islands',
'SOM':'Somalia',
'ZAF':'South Africa',
'SGS':'South Georgia and the South Sandwich Islands',
'SSD':'South Sudan',
'ESP':'Spain',
'LKA':'Sri Lanka',
'SDN':'Sudan (the)',
'SUR':'Suriname',
'SJM':'Svalbard and Jan Mayen',
'SWE':'Sweden',
'CHE':'Switzerland',
'SYR':'Syrian Arab Republic',
'TWN':'Taiwan (Province of China)',
'TJK':'Tajikistan',
'TZA':'Tanzania, United Republic of',
'THA':'Thailand',
'TLS':'Timor-Leste',
'TGO':'Togo',
'TKL':'Tokelau',
'TON':'Tonga',
'TTO':'Trinidad and Tobago',
'TUN':'Tunisia',
'TUR':'Turkey',
'TKM':'Turkmenistan',
'TCA':'Turks and Caicos Islands (the)',
'TUV':'Tuvalu',
'UGA':'Uganda',
'UKR':'Ukraine',
'ARE':'United Arab Emirates (the)',
'GBR':'United Kingdom of Great Britain and Northern Ireland',
'UMI':'United States Minor Outlying Islands',
'USA':'United States of America',
'URY':'Uruguay',
'UZB':'Uzbekistan',
'VUT':'Vanuatu',
'VEN':'Venezuela',
'VNM':'Viet Nam',
'VGB':'Virgin Islands (British)',
'VIR':'Virgin Islands (U.S.)',
'WLF':'Wallis and Futuna',
'ESH':'Western Sahara',
'YEM':'Yemen',
'ZMB':'Zambia',
'ZWE':'Zimbabwe',
'ALA':'Åland Islands',}